/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.cefetmg.space.view;

import br.cefetmg.space.model.dao.UsuarioDAO;
import br.cefetmg.space.model.idao.exception.PersistenciaException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author letic
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public Login() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JDesktopPane();
        campoUser = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoLogin = new javax.swing.JButton();
        linkCadastrar = new javax.swing.JButton();
        possuiContaLogin = new javax.swing.JLabel();
        caixaLogin = new javax.swing.JLabel();
        fundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoUser.setBackground(new java.awt.Color(89, 132, 241));
        campoUser.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        campoUser.setForeground(new java.awt.Color(255, 255, 255));
        campoUser.setToolTipText("");
        campoUser.setBorder(null);
        campoUser.setCaretColor(new java.awt.Color(255, 255, 255));
        campoUser.setDisabledTextColor(new java.awt.Color(89, 132, 241));
        campoUser.setMargin(new java.awt.Insets(0, 0, 0, 0));
        campoUser.setSelectedTextColor(new java.awt.Color(89, 132, 241));
        campoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUserActionPerformed(evt);
            }
        });
        panelLogin.add(campoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 250, 30));

        campoSenha.setBackground(new java.awt.Color(89, 132, 241));
        campoSenha.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        campoSenha.setForeground(new java.awt.Color(255, 255, 255));
        campoSenha.setBorder(null);
        campoSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        panelLogin.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 220, 30));

        botaoLogin.setBackground(new java.awt.Color(0, 102, 204));
        botaoLogin.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoLogin.setText("LOGIN");
        botaoLogin.setActionCommand("login");
        botaoLogin.setBorder(null);
        botaoLogin.setContentAreaFilled(false);
        botaoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoLoginMouseExited(evt);
            }
        });
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        panelLogin.add(botaoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 330, 90));

        linkCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        linkCadastrar.setForeground(new java.awt.Color(0, 43, 102));
        linkCadastrar.setText("Cadastrar-se");
        linkCadastrar.setContentAreaFilled(false);
        linkCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkCadastrarMouseExited(evt);
            }
        });
        linkCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkCadastrarActionPerformed(evt);
            }
        });
        panelLogin.add(linkCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 150, 30));

        possuiContaLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        possuiContaLogin.setForeground(new java.awt.Color(255, 255, 255));
        possuiContaLogin.setText("Não possui conta?");
        panelLogin.add(possuiContaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 180, -1));

        caixaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        caixaLogin.setToolTipText("");
        panelLogin.add(caixaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        fundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.png"))); // NOI18N
        fundoLogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fundoLogin.setAutoscrolls(true);
        fundoLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelLogin.add(fundoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        String user = campoUser.getText();
        String senha = new String(campoSenha.getPassword());
        try {
            if(senha.isEmpty() || user.isEmpty())
                JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");   
            else{
                if(usuarioDAO.procurarPorEmail(user) != null)
                    user = usuarioDAO.procurarPorEmail(user).getUserName();
                if(usuarioDAO.procurarPorUserName(user) != null && usuarioDAO.procurarPorUserName(user).getSenha().equals(senha)){
                    Cubesat telaCubeSat = new Cubesat();
                    this.dispose();
                    telaCubeSat.user.setText(user);
                    telaCubeSat.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Usuário ou senha incorretos.");
                 }
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void campoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUserActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLoginMouseEntered
        // TODO add your handling code here:
        botaoLogin.setForeground(new Color(89,132,241)); 
    }//GEN-LAST:event_botaoLoginMouseEntered

    private void botaoLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLoginMouseExited
        // TODO add your handling code here:
        botaoLogin.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_botaoLoginMouseExited

    private void linkCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkCadastrarActionPerformed
        // TODO add your handling code here:
        CadastroUsuario telaCadastroUsuario = new CadastroUsuario();
        this.dispose();
        telaCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_linkCadastrarActionPerformed

    private void linkCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCadastrarMouseEntered
        // TODO add your handling code here:
        linkCadastrar.setForeground(new Color(243,243,243));
    }//GEN-LAST:event_linkCadastrarMouseEntered

    private void linkCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCadastrarMouseExited
        // TODO add your handling code here:
        linkCadastrar.setForeground(new Color(0, 0, 204));
    }//GEN-LAST:event_linkCadastrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel caixaLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUser;
    private javax.swing.JLabel fundoLogin;
    private javax.swing.JButton linkCadastrar;
    private javax.swing.JDesktopPane panelLogin;
    private javax.swing.JLabel possuiContaLogin;
    // End of variables declaration//GEN-END:variables
}
